### PR TITLE
Update webguesser.yml

### PR DESCRIPTION
**Pull request by Egogre**
I didn't erase 1505 submissions in case you still needed those to archive or something

### CODE REVIEW

**Comment by jmejia** [comment]
@Egogre Can we move this update to the `1507` directory instead of `1505`?

**Comment by Egogre** [comment]
Sure. I just clicked on the link we were given and it took me to the 1505
page. Is there a 1507 page yet? If so, can you update the link on the
homework over the break page?

**Comment by jmejia** [comment]
@Egogre They've been updated for about 5-6 days.

**Comment by Egogre** [comment]
yeah, I felt more than a little foolish when I saw everyone had already
posted on the 1507 one. I don't know why the link took me to the 1505
submission page. (On second thought, I think it was because I pulled the
page up on the day you told us about it and never refreshed!)

**Pull request closed without merging**
