### PR TITLE
Update personal_site_html_css.md

### PR DESCRIPTION
**Pull request by MarisaMBurton**

### CODE REVIEW

**Comment by s-espinosa** [comment]
@MarisaMBurton Thanks! Have you been able to push to GitHub Pages? Instructions are in the intermission work, but let me know if you're having any trouble. Would like to have that address before I merge this PR.

**Comment by MarisaMBurton** [comment]
Sorry I don't understand quite what you're asking

**Comment by s-espinosa** [comment]
@MarisaMBurton I had left this message before we got the site up and running. I think all that's left to do is update the pull request so that it has the `Personal Site URL` line filled out. You should be able to just update this pull request, but if it gives you a hard time feel free to close this and open a new one.

**Comment by MarisaMBurton** [comment]
I think I sent another pull request w both the URL and the repo

**Comment by s-espinosa** [comment]
@MarisaMBurton Yup. Just saw that. Merged that one. Closing this one.

**Pull request closed without merging**
